# Generated by Django 3.2.4 on 2021-07-10 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountpledged', models.IntegerField(default=0)),
                ('timedates', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=500)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pledge', to='quickstart.pledgefeed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
