# Generated by Django 3.2.4 on 2021-07-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_userpledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpledge',
            name='pledge',
            field=models.IntegerField(default=0),
        ),
    ]
