# Generated by Django 3.2.4 on 2021-07-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_userpledge_pledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpledge',
            name='user',
            field=models.IntegerField(),
        ),
    ]
