# Generated by Django 3.2.4 on 2021-07-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_alter_userpledge_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgefeed',
            name='author',
            field=models.CharField(max_length=500),
        ),
    ]
