# Generated by Django 3.2.4 on 2021-07-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_alter_pledgefeed_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledgefeed',
            old_name='name',
            new_name='title',
        ),
    ]
