# Generated by Django 3.2.4 on 2021-07-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_alter_pledgefeed_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgefeed',
            name='deadline',
            field=models.CharField(max_length=500),
        ),
    ]
