# Generated by Django 3.2.4 on 2021-07-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_alter_pledgefeed_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpledge',
            name='pledge',
            field=models.CharField(max_length=500),
        ),
    ]
