# Generated by Django 3.2.4 on 2021-07-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_auto_20210715_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpledge',
            name='user',
            field=models.CharField(max_length=500),
        ),
    ]
